/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gabrielamontes__lab5p2;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTree;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;

/**
 *
 * @author Gabriela Montes
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
        tmodel.addColumn("Nombre");
        tmodel.addColumn("Poder");
        tmodel.addColumn("Debilidad");
        tmodel.addColumn("Universo");
        tmodel.addColumn("Fuerza");
        tmodel.addColumn("Agilidad Fisica");
        tmodel.addColumn("Agilidad mental");
        tmodel.addColumn("Puntos de vida");
        jt_listar.setModel(tmodel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jf_crear = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        tf_poder = new javax.swing.JTextField();
        tf_debilidad = new javax.swing.JTextField();
        js_fuerza = new javax.swing.JSpinner();
        js_fisica = new javax.swing.JSpinner();
        js_mental = new javax.swing.JSpinner();
        js_hp = new javax.swing.JSpinner();
        jb_agregar = new javax.swing.JButton();
        cb_universo = new javax.swing.JComboBox<>();
        jb_regresarcrear = new javax.swing.JButton();
        jd_crud = new javax.swing.JDialog();
        jb_crear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jf_tree = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_Personajes = new javax.swing.JTree();
        jl_nombre = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_elements = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_listar = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        pp_eliminar = new javax.swing.JPopupMenu();
        jmi_eliminar = new javax.swing.JMenuItem();
        jf_simulacion = new javax.swing.JFrame();
        cb_select = new javax.swing.JComboBox<>();
        combobox_select2 = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_personaje1 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jl_personaje2 = new javax.swing.JList<>();
        jb_batalla = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jf_batalla = new javax.swing.JFrame();
        jlabel_jugador = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ja_pelea = new javax.swing.JTextArea();
        jb_fuerza = new javax.swing.JButton();
        jb_mental = new javax.swing.JButton();
        jb_resistencia = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jb_crud = new javax.swing.JButton();
        jb_listar = new javax.swing.JButton();
        jb_simulacion = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crear");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Poder");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Debilidad");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Universo");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Fuerza");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Agilidad fisica");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Agilidad mental");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Puntos de vida");

        tf_nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tf_poder.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tf_debilidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        js_fuerza.setModel(new javax.swing.SpinnerNumberModel());

        js_fisica.setModel(new javax.swing.SpinnerNumberModel());

        js_mental.setModel(new javax.swing.SpinnerNumberModel());

        js_hp.setModel(new javax.swing.SpinnerNumberModel());

        jb_agregar.setText("Agregar");
        jb_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarMouseClicked(evt);
            }
        });

        cb_universo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DC", "Marvel", "Capcom", "Mortal Kombat", " " }));
        cb_universo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_universoActionPerformed(evt);
            }
        });

        jb_regresarcrear.setText("regresar");
        jb_regresarcrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_regresarcrearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jf_crearLayout = new javax.swing.GroupLayout(jf_crear.getContentPane());
        jf_crear.getContentPane().setLayout(jf_crearLayout);
        jf_crearLayout.setHorizontalGroup(
            jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_crearLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_crearLayout.createSequentialGroup()
                        .addGroup(jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jf_crearLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(js_hp, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jf_crearLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                                .addComponent(js_mental, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jf_crearLayout.createSequentialGroup()
                                .addGroup(jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_poder)
                                    .addComponent(tf_nombre)
                                    .addComponent(tf_debilidad, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                                    .addComponent(js_fuerza, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_universo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jf_crearLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(js_fisica, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_crearLayout.createSequentialGroup()
                        .addComponent(jb_regresarcrear)
                        .addGap(44, 44, 44)
                        .addComponent(jb_agregar)
                        .addGap(115, 115, 115))))
        );
        jf_crearLayout.setVerticalGroup(
            jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_crearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_poder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_debilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cb_universo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(js_fuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(js_fisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(js_mental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(js_hp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_agregar)
                    .addComponent(jb_regresarcrear))
                .addGap(41, 41, 41))
        );

        jb_crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gabrielamontes__lab5p2/icons8-pixel-star-100.png"))); // NOI18N
        jb_crear.setText("Crear");
        jb_crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Personajes");

        javax.swing.GroupLayout jd_crudLayout = new javax.swing.GroupLayout(jd_crud.getContentPane());
        jd_crud.getContentPane().setLayout(jd_crudLayout);
        jd_crudLayout.setHorizontalGroup(
            jd_crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crudLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crudLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jb_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jd_crudLayout.setVerticalGroup(
            jd_crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crudLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jb_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Personajes");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("DC");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Marvel");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Capcom");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Mortal Kombat");
        treeNode1.add(treeNode2);
        jt_Personajes.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_Personajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_PersonajesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_Personajes);

        jl_nombre.setText("jLabel11");

        jScrollPane2.setViewportView(jl_elements);

        jt_listar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jt_listar);

        jButton1.setText("Regresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jf_treeLayout = new javax.swing.GroupLayout(jf_tree.getContentPane());
        jf_tree.getContentPane().setLayout(jf_treeLayout);
        jf_treeLayout.setHorizontalGroup(
            jf_treeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_treeLayout.createSequentialGroup()
                .addGroup(jf_treeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_treeLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jf_treeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_treeLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(131, 131, 131)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jf_treeLayout.setVerticalGroup(
            jf_treeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_treeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jf_treeLayout.createSequentialGroup()
                .addGroup(jf_treeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_treeLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jl_nombre)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jf_treeLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );

        jmi_eliminar.setText("Eliminar\n");
        jmi_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_eliminarActionPerformed(evt);
            }
        });
        pp_eliminar.add(jmi_eliminar);

        cb_select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DC", "Marvel", "Capcom", "Mortal Kombat" }));
        cb_select.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_selectMouseClicked(evt);
            }
        });

        combobox_select2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DC", "Marvel", "Capcom", "Mortal Kombat" }));
        combobox_select2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combobox_select2MouseClicked(evt);
            }
        });
        combobox_select2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_select2ActionPerformed(evt);
            }
        });

        jl_personaje1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_personaje1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jl_personaje1);

        jScrollPane5.setViewportView(jl_personaje2);

        jb_batalla.setText("BATALLA!");
        jb_batalla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_batallaMouseClicked(evt);
            }
        });
        jb_batalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_batallaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jf_simulacionLayout = new javax.swing.GroupLayout(jf_simulacion.getContentPane());
        jf_simulacion.getContentPane().setLayout(jf_simulacionLayout);
        jf_simulacionLayout.setHorizontalGroup(
            jf_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_simulacionLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jf_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_simulacionLayout.createSequentialGroup()
                        .addComponent(cb_select, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(combobox_select2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188))
                    .addGroup(jf_simulacionLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))))
            .addGroup(jf_simulacionLayout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(jb_batalla, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jf_simulacionLayout.setVerticalGroup(
            jf_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_simulacionLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jf_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox_select2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jf_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jb_batalla)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setText("Darle clic a un personaje de cada lista");

        ja_pelea.setColumns(20);
        ja_pelea.setRows(5);
        jScrollPane6.setViewportView(ja_pelea);

        jb_fuerza.setText("Fuerza");
        jb_fuerza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_fuerzaMouseClicked(evt);
            }
        });

        jb_mental.setText("Mental");
        jb_mental.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_mentalMouseClicked(evt);
            }
        });

        jb_resistencia.setText("Resistencia");
        jb_resistencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_resistenciaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jf_batallaLayout = new javax.swing.GroupLayout(jf_batalla.getContentPane());
        jf_batalla.getContentPane().setLayout(jf_batallaLayout);
        jf_batallaLayout.setHorizontalGroup(
            jf_batallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_batallaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jf_batallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabel_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(jf_batallaLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jb_fuerza)
                .addGap(150, 150, 150)
                .addComponent(jb_mental)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_resistencia)
                .addGap(110, 110, 110))
        );
        jf_batallaLayout.setVerticalGroup(
            jf_batallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_batallaLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jlabel_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jf_batallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_fuerza)
                    .addComponent(jb_mental)
                    .addComponent(jb_resistencia))
                .addGap(30, 30, 30))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jb_crud.setText("Agregar Personajes");
        jb_crud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crudMouseClicked(evt);
            }
        });

        jb_listar.setText("Listar");
        jb_listar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_listarMouseClicked(evt);
            }
        });

        jb_simulacion.setText("Simulacion");
        jb_simulacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_simulacionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jb_crud)
                .addGap(30, 30, 30)
                .addComponent(jb_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jb_simulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_crud, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_simulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_crudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crudMouseClicked
        jd_crud.setModal(true);
        jd_crud.pack();
        jd_crud.setLocationRelativeTo(this);
        jd_crud.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jb_crudMouseClicked

    private void jb_crearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearMouseClicked
        jf_crear.pack();
        jf_crear.setLocationRelativeTo(jd_crud);
        jd_crud.setVisible(false);
        jf_crear.setVisible(true);

    }//GEN-LAST:event_jb_crearMouseClicked

    private void jb_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarMouseClicked
        Personaje p = new Personaje();
        p.setNombre(tf_nombre.getText());
        p.setPoder(tf_poder.getText());
        p.setDebilidad(tf_debilidad.getText());
        p.setUniverso(cb_universo.getSelectedItem().toString());
        p.setFuerza(Integer.parseInt(js_fuerza.getValue().toString()));
        p.setAfisica(Integer.parseInt(js_fisica.getValue().toString()));
        p.setAmental(Integer.parseInt(js_mental.getValue().toString()));
        p.setVida(Integer.parseInt(js_hp.getValue().toString()));
        p.setValid(true);
        personajes.add(p);
        DefaultTreeModel m = (DefaultTreeModel) jt_Personajes.getModel();
        DefaultMutableTreeNode raiz
                = (DefaultMutableTreeNode) m.getRoot();
        for (int i = 0; i < raiz.getChildCount(); i++) {
            if (((raiz.getChildAt(i).toString()).equals((p.getUniverso())))) {
                DefaultMutableTreeNode nodo = new DefaultMutableTreeNode(p);
                ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(nodo);
            }
        }
        m.reload();
        tf_nombre.setText("");
        tf_poder.setText("");
        tf_debilidad.setText("");
        cb_universo.setSelectedIndex(0);
        js_fuerza.setValue(0);
        js_fisica.setValue(0);
        js_hp.setValue(0);
        js_mental.setValue(0);
        JOptionPane.showConfirmDialog(jf_crear, "Personaje Agregado");
    }//GEN-LAST:event_jb_agregarMouseClicked

    private void jb_listarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_listarMouseClicked
        jf_tree.pack();
        jf_tree.setLocationRelativeTo(this);
        this.setVisible(false);
        jf_tree.setVisible(true);
    }//GEN-LAST:event_jb_listarMouseClicked

    private void jt_PersonajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_PersonajesMouseClicked

        //izquierda a derecha
        if (evt.isMetaDown()) {
            int row = jt_Personajes.getClosestRowForLocation(
                    evt.getX(), evt.getY());
            jt_Personajes.setSelectionRow(row);
            Object v1
                    = jt_Personajes.getSelectionPath().
                            getLastPathComponent();
            DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) v1;
            DefaultTreeModel m = (DefaultTreeModel) jt_Personajes.getModel();
            DefaultMutableTreeNode raiz
                    = (DefaultMutableTreeNode) m.getRoot();

            if (nodo.equals(raiz.getChildAt(0))) {
                tabla(0);
            } else if (nodo.equals(raiz.getChildAt(1))) {
                tabla(1);
            } else if (nodo.equals(raiz.getChildAt(2))) {
                tabla(2);
            } else if (nodo.equals(raiz.getChildAt(3))) {
                tabla(3);
            } else {
                jl_nombre.setText(nodo.toString());
                for (Personaje p : personajes) {
                    p.setValid(true);
                    if (nodo.toString().equals(p.toString())) {
                        listar(p);
                        pp_eliminar.show(evt.getComponent(),
                                evt.getX(), evt.getY());
                    }
                }
            }

        }

    }//GEN-LAST:event_jt_PersonajesMouseClicked

    private void combobox_select2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_select2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_select2ActionPerformed

    private void cb_universoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_universoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_universoActionPerformed

    private void jmi_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_eliminarActionPerformed
        int row = jt_Personajes.getClosestRowForLocation(WIDTH, WIDTH);
        jt_Personajes.setSelectionRow(row);
        Object v1
                = jt_Personajes.getSelectionPath().
                        getLastPathComponent();
        DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) v1;
        DefaultTreeModel m = (DefaultTreeModel) jt_Personajes.getModel();
        DefaultMutableTreeNode raiz
                = (DefaultMutableTreeNode) m.getRoot();
        for (Personaje p : personajes) {
            p.setValid(false);
            if (nodo.toString().equals(p.toString())) {
                eliminar(nodo, p);
            }
        }

    }//GEN-LAST:event_jmi_eliminarActionPerformed

    private void jb_regresarcrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_regresarcrearMouseClicked
        tf_nombre.setText("");
        tf_poder.setText("");
        tf_debilidad.setText("");
        cb_universo.setSelectedIndex(0);
        js_fuerza.setValue(0);
        js_fisica.setValue(0);
        js_hp.setValue(0);
        js_mental.setValue(0);
        jf_crear.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jb_regresarcrearMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
      this.pack();
        this.setLocationRelativeTo(jf_tree);
        jf_tree.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jb_simulacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_simulacionMouseClicked
        jf_simulacion.pack();
        jf_simulacion.setLocationRelativeTo(jd_crud);
        this.setVisible(false);
        jf_simulacion.setVisible(true);
    }//GEN-LAST:event_jb_simulacionMouseClicked

    private void cb_selectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_selectMouseClicked
        String nombre = cb_select.getSelectedItem().toString();
        l2model.removeAllElements();
        if (nombre.equals("DC")) {
            listarper(0, l2model, jl_personaje1);
        } else if (nombre.equals("Marvel")) {
            listarper(1, l2model, jl_personaje1);
        } else if (nombre.equals("Capcom")) {
            listarper(2, l2model, jl_personaje1);
        } else {
            listarper(3, l2model, jl_personaje1);
        }
    }//GEN-LAST:event_cb_selectMouseClicked

    private void combobox_select2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combobox_select2MouseClicked
        String name = combobox_select2.getSelectedItem().toString();
        l3model.removeAllElements();
        if (name.equals("DC")) {
            listarper2(0, l3model, jl_personaje2);
        } else if (name.equals("Marvel")) {
            listarper2(1, l3model, jl_personaje2);
        } else if (name.equals("Capcom")) {
            listarper2(2, l3model, jl_personaje2);
        } else {
            listarper2(3, l3model, jl_personaje2);
        }
    }//GEN-LAST:event_combobox_select2MouseClicked

    private void jl_personaje1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_personaje1MouseClicked

    }//GEN-LAST:event_jl_personaje1MouseClicked

    private void jb_batallaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_batallaMouseClicked
        jf_batalla.pack();
        jf_batalla.setLocationRelativeTo(jf_simulacion);
        jf_simulacion.setVisible(false);
        jf_batalla.setVisible(true);
    }//GEN-LAST:event_jb_batallaMouseClicked

    private void jb_mentalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_mentalMouseClicked
        int l = new Random().nextInt((100 - 1) + 1) + 1;
        ArrayList<Personaje> ps = new ArrayList();
        ps = jugadores();
        Personaje p = ps.get(0);
        Personaje p1 = ps.get(1);
        if (p.isDoble() == true) {
            JOptionPane.showMessageDialog(jf_batalla, "turno perdido");
            p.setDoble(false);
        } else if (p1.isDoble() == true) {
            JOptionPane.showMessageDialog(jf_batalla, "turno perdido");
            p.setDoble(false);
        } else {
            int vida = p.getVida();
            int vida2 = p1.getVida();
            if (vida > 0 && vida2 > 0) {
                if (l <= 15) {
                    if (p.isTurno() == true) {
                        jlabel_jugador.setText(p.getNombre());
                        jlabel_jugador.setBackground(Color.red);
                        int ataque = ((int) (0.33 * p.getAmental())) * 2;
                        vida2 -= ataque;
                        p1.setVida(vida2);
                        p.setTurno(false);
                        p1.setTurno(true);
                        ja_pelea.setText(p.getNombre() + "hizo un ataque mental a " + p1.getNombre() + "y sus puntos de vida ahora son: " + vida2);
                    } else {
                        jlabel_jugador.setText(p1.getNombre());
                        jlabel_jugador.setBackground(Color.BLUE);
                        int ataque = ((int) (0.33 * p1.getAmental())) * 2;
                        vida -= ataque;
                        p.setVida(vida);
                        p.setTurno(true);
                        p1.setTurno(false);
                        ja_pelea.setText(p1.getNombre() + "hizo un ataque de fuerza a " + p.getNombre() + "y sus puntos de vida ahora son: " + vida);
                    }
                } else {
                    if (p.isTurno() == true) {
                        jlabel_jugador.setText(p.getNombre());
                        jlabel_jugador.setBackground(Color.red);
                        int ataque = ((int) (0.33 * p.getAmental()));
                        vida2 -= ataque;
                        p1.setVida(vida2);
                        p.setTurno(false);
                        p1.setTurno(true);
                        ja_pelea.setText(p.getNombre() + "hizo un ataque mental a " + p1.getNombre() + "y sus puntos de vida ahora son: " + vida2);
                    } else {
                        jlabel_jugador.setText(p1.getNombre());
                        jlabel_jugador.setBackground(Color.BLUE);
                        int ataque = ((int) (0.33 * p1.getAmental()));
                        vida -= ataque;
                        p.setVida(vida);
                        p.setTurno(true);
                        p1.setTurno(false);
                        ja_pelea.setText(p1.getNombre() + "hizo un ataque de fuerza a " + p.getNombre() + "y sus puntos de vida ahora son: " + vida);
                    }
                }
            } else {
                if (vida > vida2) {
                    System.out.println("Gana jugador 1");
                } else {
                    System.out.println("Gana jugador 2");
                }
            }
        }
    }//GEN-LAST:event_jb_mentalMouseClicked

    private void jb_resistenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_resistenciaMouseClicked
        ArrayList<Personaje> ps = new ArrayList();
        ps = jugadores();
        Personaje p = ps.get(0);
        Personaje p1 = ps.get(1);
        if (p.isDoble() == true) {
            JOptionPane.showMessageDialog(jf_batalla, "turno perdido");
            p.setDoble(false);
        } else if (p1.isDoble() == true) {
            JOptionPane.showMessageDialog(jf_batalla, "turno perdido");
            p.setDoble(false);
        } else {
            int vida = p.getVida();
            int vida2 = p1.getVida();
            if (vida > 0 && vida2 > 0) {
                if (p.isTurno() == true) {
                    int fuerza = (int) (p.getFuerza() * 0.15);
                    jlabel_jugador.setText(p.getNombre());
                    jlabel_jugador.setBackground(Color.red);
                    vida += fuerza;
                    p.setDoble(true);
                    p.setTurno(false);
                    p1.setTurno(true);
                    p.setVida(vida);
                    ja_pelea.setText(p.getNombre() + " hizo un ataque de resistencia a " + p1.getNombre() + "y aumento su propia vida a: " + vida);
                } else {
                    jlabel_jugador.setText(p1.getNombre());
                    jlabel_jugador.setBackground(Color.BLUE);
                    int fuerza = (int) (p1.getFuerza() * 0.15);
                    vida2 += fuerza;
                    p1.setVida(vida2);
                    p.setDoble(true);
                    p.setTurno(true);
                    p1.setTurno(false);
                    ja_pelea.setText(p1.getNombre() + " hizo un ataque de resistencia a " + p.getNombre() + "y aumento su propia vida a: " + vida2);
                }

            } else {
                if (vida > vida2) {
                    System.out.println("Gana jugador 1");
                } else {
                    System.out.println("Gana jugador 2");
                }
            }
        }
    }//GEN-LAST:event_jb_resistenciaMouseClicked

    private void jb_fuerzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_fuerzaMouseClicked
        int l = new Random().nextInt((100 - 1) + 1) + 1;
        ArrayList<Personaje> ps = new ArrayList();
        ps = jugadores();
        Personaje p = ps.get(0);
        Personaje p1 = ps.get(1);
        if (p.isDoble() == true) {
            JOptionPane.showMessageDialog(jf_batalla, "turno perdido");
            p.setDoble(false);
        } else if (p1.isDoble() == true) {
            JOptionPane.showMessageDialog(jf_batalla, "turno perdido");
            p.setDoble(false);
        } else {
            int vida = p.getVida();
            int vida2 = p1.getVida();
            if (vida > 0 && vida2 > 0) {
                if (l <= 8) {
                    if (p.isTurno() == true) {
                        jlabel_jugador.setText(p.getNombre());
                        jlabel_jugador.setBackground(Color.red);
                        int ataque = (int) (((int) (0.2 * p.getAmental())) * 0.25);
                        vida2 -= ataque;
                        p1.setVida(vida2);
                        p.setTurno(false);
                        p1.setTurno(true);
                        ja_pelea.setText(p.getNombre() + "hizo un ataque de fuerza a " + p1.getNombre() + "y sus puntos de vida ahora son: " + vida2);
                    } else {
                        jlabel_jugador.setText(p1.getNombre());
                        jlabel_jugador.setBackground(Color.BLUE);
                        int ataque = (int) (((int) (0.2 * p1.getAmental())) * 0.25);
                        vida -= ataque;
                        p.setVida(vida);
                        p.setTurno(true);
                        p1.setTurno(false);
                        ja_pelea.setText(p1.getNombre() + "hizo un ataque de fuerza a " + p.getNombre() + "y sus puntos de vida ahora son: " + vida);
                    }
                } else {
                    if (p.isTurno() == true) {
                        jlabel_jugador.setText(p.getNombre());
                        jlabel_jugador.setBackground(Color.red);
                        int ataque = (((int) (0.2 * p.getAmental())));
                        vida2 -= ataque;
                        p1.setVida(vida2);
                        p.setTurno(false);
                        p1.setTurno(true);
                        ja_pelea.setText(p.getNombre() + "hizo un ataque de fuerza a " + p1.getNombre() + "y sus puntos de vida ahora son: " + vida2);
                    } else {
                        jlabel_jugador.setText(p1.getNombre());
                        jlabel_jugador.setBackground(Color.BLUE);
                        int ataque = ((int) (0.2 * p1.getAmental()));
                        vida -= ataque;
                        p.setVida(vida);
                        p.setTurno(true);
                        p1.setTurno(false);
                        ja_pelea.setText(p1.getNombre() + "hizo un ataque de fuerza a " + p.getNombre() + "y sus puntos de vida ahora son: " + vida);
                    }
                }
            } else {
                if (vida > vida2) {
                    System.out.println("Gana jugador 1");
                } else {
                    System.out.println("Gana jugador 2");
                }
            }
        }
    }//GEN-LAST:event_jb_fuerzaMouseClicked

    private void jb_batallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_batallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_batallaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_select;
    private javax.swing.JComboBox<String> cb_universo;
    private javax.swing.JComboBox<String> combobox_select2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea ja_pelea;
    private javax.swing.JButton jb_agregar;
    private javax.swing.JButton jb_batalla;
    private javax.swing.JButton jb_crear;
    private javax.swing.JButton jb_crud;
    private javax.swing.JButton jb_fuerza;
    private javax.swing.JButton jb_listar;
    private javax.swing.JButton jb_mental;
    private javax.swing.JButton jb_regresarcrear;
    private javax.swing.JButton jb_resistencia;
    private javax.swing.JButton jb_simulacion;
    private javax.swing.JDialog jd_crud;
    private javax.swing.JFrame jf_batalla;
    private javax.swing.JFrame jf_crear;
    private javax.swing.JFrame jf_simulacion;
    private javax.swing.JFrame jf_tree;
    private javax.swing.JList<String> jl_elements;
    private javax.swing.JLabel jl_nombre;
    private javax.swing.JList<String> jl_personaje1;
    private javax.swing.JList<String> jl_personaje2;
    private javax.swing.JLabel jlabel_jugador;
    private javax.swing.JMenuItem jmi_eliminar;
    private javax.swing.JSpinner js_fisica;
    private javax.swing.JSpinner js_fuerza;
    private javax.swing.JSpinner js_hp;
    private javax.swing.JSpinner js_mental;
    private javax.swing.JTree jt_Personajes;
    private javax.swing.JTable jt_listar;
    private javax.swing.JPopupMenu pp_eliminar;
    private javax.swing.JTextField tf_debilidad;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_poder;
    // End of variables declaration//GEN-END:variables
DefaultTableModel tmodel = new DefaultTableModel();

    ArrayList<Personaje> personajes = new ArrayList();
    DefaultListModel lmodel = new DefaultListModel();
    DefaultListModel l2model = new DefaultListModel();
    DefaultListModel l3model = new DefaultListModel();

    public void listar(Personaje p) {
        lmodel.removeAllElements();
        jl_elements.setModel(lmodel);
        Object[] el = {"nombre -> " + p.getNombre(), "poder -> " + p.getPoder(), "Debilidad -> " + p.getDebilidad(), "Universo -> " + p.getUniverso(), "Fuerza -> " + p.getFuerza(), "Abilidad fisica-> " + p.getAfisica(), "Abilidad mental -> " + p.getAmental(), "Puntos de vida -> " + p.getVida()};
        for (Object o : el) {
            lmodel.addElement(o);
        }
        jl_elements.setModel(lmodel);

    }

    public void listarper(int index, DefaultListModel e, JList l) {
        e.removeAllElements();
        l.setModel(e);
        for (Personaje p : personajes) {
            p.setValid(true);
            if (index == 0) {
                if (p.getUniverso().equals("DC")) {
                    e.addElement(p);
                }

            } else if (index == 1) {
                if (p.getUniverso().equals("Marvel")) {
                    e.addElement(p);
                }
            } else if (index == 2) {
                if (p.getUniverso().equals("Capcom")) {
                    e.addElement(p);
                }
            } else if (index == 3) {
                if (p.getUniverso().equals("Mortal Kombat")) {
                    e.addElement(p);
                }
            }
            
        }
        l.setModel(e);
    }

    public void listarper2(int index, DefaultListModel e, JList l) {
        e.removeAllElements();
        l.setModel(e);
        for (Personaje p : personajes) {
            p.setValid(true);
            if (index == 0) {
                if (p.getUniverso().equals("DC")) {
                    e.addElement(p);
                }

            } else if (index == 1) {
                if (p.getUniverso().equals("Marvel")) {
                    e.addElement(p);
                }
            } else if (index == 2) {
                if (p.getUniverso().equals("Capcom")) {
                    e.addElement(p);
                }
            } else if (index == 3) {
                if (p.getUniverso().equals("Mortal Kombat")) {
                    e.addElement(p);
                }
            }
        }
         l.setModel(e);
    }

    public void tabla(int index) {
        //nombre, poder, debilidad, universo, fuerza, afisica, amental, vida;
        while (tmodel.getRowCount() > 0) {
            tmodel.removeRow(0);
        }
        for (Personaje p : personajes) {
            if (index == 0) {
                if (p.getUniverso().equals("DC")) {
                    Object[] row = {p.getNombre(), p.getPoder(), p.getDebilidad(), p.getUniverso(), p.getFuerza(), p.getAfisica(), p.getAmental(), p.getVida()};
                    DefaultTableModel modelo = (DefaultTableModel) jt_listar.getModel();
                    modelo.addRow(row);
                    jt_listar.setModel(modelo);
                }

            } else if (index == 1) {
                if (p.getUniverso().equals("Marvel")) {
                    Object[] row = {p.getNombre(), p.getPoder(), p.getDebilidad(), p.getUniverso(), p.getFuerza(), p.getAfisica(), p.getAmental(), p.getVida()};
                    DefaultTableModel modelo = (DefaultTableModel) jt_listar.getModel();
                    modelo.addRow(row);
                    jt_listar.setModel(modelo);
                }
            } else if (index == 2) {
                if (p.getUniverso().equals("Capcom")) {
                    Object[] row = {p.getNombre(), p.getPoder(), p.getDebilidad(), p.getUniverso(), p.getFuerza(), p.getAfisica(), p.getAmental(), p.getVida()};
                    DefaultTableModel modelo = (DefaultTableModel) jt_listar.getModel();
                    modelo.addRow(row);
                    jt_listar.setModel(modelo);
                }
            } else if (index == 3) {
                if (p.getUniverso().equals("Mortal Kombat")) {
                    Object[] row = {p.getNombre(), p.getPoder(), p.getDebilidad(), p.getUniverso(), p.getFuerza(), p.getAfisica(), p.getAmental(), p.getVida()};
                    DefaultTableModel modelo = (DefaultTableModel) jt_listar.getModel();
                    modelo.addRow(row);
                    jt_listar.setModel(modelo);
                }
            }
        }
    }

    public void eliminar(DefaultMutableTreeNode h, Personaje c) {
        DefaultTreeModel m = (DefaultTreeModel) jt_Personajes.getModel();
        DefaultMutableTreeNode raiz
                = (DefaultMutableTreeNode) m.getRoot();
        for (int i = 0; i < raiz.getChildCount(); i++) {
            for (int j = 0; j < raiz.getChildAt(i).getChildCount(); j++) {
                if (((raiz.getChildAt(i).getChildAt(j).toString()).equals((h.toString())))) {
                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).remove(j);
                }

            }
        }
        for (Personaje p : personajes) {
            if (p.equals(c)) {
                personajes.remove(p);
            }
        }

        m.reload();

    }

    public ArrayList jugadores() {
        String per1 = jl_personaje1.getSelectedValue();
        String per2 = jl_personaje2.getSelectedValue();
        Personaje jugador = new Personaje();
        Personaje jugador2 = new Personaje();
        for (Personaje p : personajes) {
            p.setValid(true);
            if (per1.equals(p.toString())) {
                jugador = p;
                jugador.setTurno(true);
                jugador.setDoble(false);
            }
            if (per1.equals(p.toString())) {
                jugador2 = p;
                jugador2.setTurno(false);
                jugador2.setDoble(false);
            }
        }
        int vida1 = jugador.getVida();
        int vida2 = jugador2.getVida();
        ArrayList<Personaje> jugadores = new ArrayList();
        jugadores.add(jugador);
        jugadores.add(jugador2);
        return jugadores;
    }
}
