/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gabrielamontes__lab5p2;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;

/**
 *
 * @author Gabriela Montes
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
        tmodel.addColumn("Nombre");
    tmodel.addColumn("Poder");
    tmodel.addColumn("Debilidad");
    tmodel.addColumn("Universo");
    tmodel.addColumn("Fuerza");
    tmodel.addColumn("Agilidad Fisica");
    tmodel.addColumn("Agilidad mental");
    tmodel.addColumn("Puntos de vida");
    jt_listar.setModel(tmodel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jf_crear = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        tf_poder = new javax.swing.JTextField();
        tf_debilidad = new javax.swing.JTextField();
        js_fuerza = new javax.swing.JSpinner();
        js_fisica = new javax.swing.JSpinner();
        js_mental = new javax.swing.JSpinner();
        js_hp = new javax.swing.JSpinner();
        jb_agregar = new javax.swing.JButton();
        cb_universo = new javax.swing.JComboBox<>();
        jd_crud = new javax.swing.JDialog();
        jb_crear = new javax.swing.JButton();
        jb_eliminar = new javax.swing.JButton();
        jb_mod = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jf_tree = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_Personajes = new javax.swing.JTree();
        jl_nombre = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_elements = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_listar = new javax.swing.JTable();
        jf_eliminar = new javax.swing.JFrame();
        jLabel21 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_pos = new javax.swing.JTextField();
        jb_remove = new javax.swing.JButton();
        pp_listartable = new javax.swing.JPopupMenu();
        pp_listarlista = new javax.swing.JPopupMenu();
        jf_simulacion = new javax.swing.JFrame();
        cb_select = new javax.swing.JComboBox<>();
        jc_select2 = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jb_crud = new javax.swing.JButton();
        jb_listar = new javax.swing.JButton();
        jb_simulacion = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crear");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Poder");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Debilidad");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Universo");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Fuerza");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Agilidad fisica");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Agilidad mental");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Puntos de vida");

        tf_nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tf_poder.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tf_debilidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        js_fuerza.setModel(new javax.swing.SpinnerNumberModel());

        js_fisica.setModel(new javax.swing.SpinnerNumberModel());

        js_mental.setModel(new javax.swing.SpinnerNumberModel());

        js_hp.setModel(new javax.swing.SpinnerNumberModel());

        jb_agregar.setText("Agregar");
        jb_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarMouseClicked(evt);
            }
        });

        cb_universo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DC", "Marvel", "Capcom", "Mortal Kombat", " " }));
        cb_universo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_universoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jf_crearLayout = new javax.swing.GroupLayout(jf_crear.getContentPane());
        jf_crear.getContentPane().setLayout(jf_crearLayout);
        jf_crearLayout.setHorizontalGroup(
            jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_crearLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_crearLayout.createSequentialGroup()
                        .addGroup(jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jf_crearLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(js_hp, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jf_crearLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                                .addComponent(js_mental, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jf_crearLayout.createSequentialGroup()
                                .addGroup(jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_poder)
                                    .addComponent(tf_nombre)
                                    .addComponent(tf_debilidad, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                                    .addComponent(js_fuerza, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_universo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jf_crearLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(js_fisica, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_crearLayout.createSequentialGroup()
                        .addComponent(jb_agregar)
                        .addGap(115, 115, 115))))
        );
        jf_crearLayout.setVerticalGroup(
            jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_crearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_poder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_debilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cb_universo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(js_fuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(js_fisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(js_mental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jf_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(js_hp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jb_agregar)
                .addGap(41, 41, 41))
        );

        jb_crear.setText("Crear");
        jb_crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearMouseClicked(evt);
            }
        });

        jb_eliminar.setText("Eliminar");
        jb_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_eliminarMouseClicked(evt);
            }
        });

        jb_mod.setText("Modificar");
        jb_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Personajes");

        javax.swing.GroupLayout jd_crudLayout = new javax.swing.GroupLayout(jd_crud.getContentPane());
        jd_crud.getContentPane().setLayout(jd_crudLayout);
        jd_crudLayout.setHorizontalGroup(
            jd_crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crudLayout.createSequentialGroup()
                .addGroup(jd_crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crudLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jd_crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_crear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_mod, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)))
                    .addGroup(jd_crudLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jd_crudLayout.setVerticalGroup(
            jd_crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crudLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(jb_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_mod)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Personajes");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("DC");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Marvel");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Capcom");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Mortal Kombat");
        treeNode1.add(treeNode2);
        jt_Personajes.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_Personajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_PersonajesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_Personajes);

        jl_nombre.setText("jLabel11");

        jScrollPane2.setViewportView(jl_elements);

        jt_listar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jt_listar);

        javax.swing.GroupLayout jf_treeLayout = new javax.swing.GroupLayout(jf_tree.getContentPane());
        jf_tree.getContentPane().setLayout(jf_treeLayout);
        jf_treeLayout.setHorizontalGroup(
            jf_treeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_treeLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jf_treeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jf_treeLayout.setVerticalGroup(
            jf_treeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_treeLayout.createSequentialGroup()
                .addGroup(jf_treeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_treeLayout.createSequentialGroup()
                        .addGroup(jf_treeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jf_treeLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jl_nombre)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jf_treeLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_treeLayout.createSequentialGroup()
                        .addGap(0, 60, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Eliminar");

        jLabel12.setText("nombre");

        jb_remove.setText("Eliminar");
        jb_remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_removeMouseClicked(evt);
            }
        });
        jb_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_removeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jf_eliminarLayout = new javax.swing.GroupLayout(jf_eliminar.getContentPane());
        jf_eliminar.getContentPane().setLayout(jf_eliminarLayout);
        jf_eliminarLayout.setHorizontalGroup(
            jf_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jf_eliminarLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(tf_pos, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_eliminarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_remove)
                .addGap(123, 123, 123))
        );
        jf_eliminarLayout.setVerticalGroup(
            jf_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_eliminarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jf_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_pos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jb_remove)
                .addGap(15, 15, 15))
        );

        cb_select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DC", "Marvel", "Capcom", "Mortal Kombat" }));
        cb_select.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cb_selectMouseEntered(evt);
            }
        });

        jc_select2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DC", "Marvel", "Capcom", "Mortal Kombat" }));
        jc_select2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_select2ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList2);

        javax.swing.GroupLayout jf_simulacionLayout = new javax.swing.GroupLayout(jf_simulacion.getContentPane());
        jf_simulacion.getContentPane().setLayout(jf_simulacionLayout);
        jf_simulacionLayout.setHorizontalGroup(
            jf_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_simulacionLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jf_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_simulacionLayout.createSequentialGroup()
                        .addComponent(cb_select, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jc_select2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188))
                    .addGroup(jf_simulacionLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))))
        );
        jf_simulacionLayout.setVerticalGroup(
            jf_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_simulacionLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jf_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jc_select2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jf_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jb_crud.setText("Agregar Personajes");
        jb_crud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crudMouseClicked(evt);
            }
        });

        jb_listar.setText("Listar");
        jb_listar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_listarMouseClicked(evt);
            }
        });

        jb_simulacion.setText("Simulacion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jb_crud)
                .addGap(30, 30, 30)
                .addComponent(jb_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jb_simulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_crud, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_simulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_crudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crudMouseClicked
        jd_crud.setModal(true);
        jd_crud.pack();
        jd_crud.setLocationRelativeTo(this);
        jd_crud.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jb_crudMouseClicked

    private void jb_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_modActionPerformed

    private void jb_crearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearMouseClicked
        jf_crear.pack();
        jf_crear.setLocationRelativeTo(jd_crud);
        jf_crear.setVisible(true);
        jd_crud.setVisible(false);

    }//GEN-LAST:event_jb_crearMouseClicked

    private void jb_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarMouseClicked
        Personaje p = new Personaje();
        p.setNombre(tf_nombre.getText());
        p.setPoder(tf_poder.getText());
        p.setDebilidad(tf_debilidad.getText());
        p.setUniverso(cb_universo.getSelectedItem().toString());
        p.setFuerza(Integer.parseInt(js_fuerza.getValue().toString()));
        p.setAfisica(Integer.parseInt(js_fisica.getValue().toString()));
        p.setAmental(Integer.parseInt(js_mental.getValue().toString()));
        p.setVida(Integer.parseInt(js_hp.getValue().toString()));
        p.setValid(true);
        personajes.add(p);
        DefaultTreeModel m = (DefaultTreeModel) jt_Personajes.getModel();
        DefaultMutableTreeNode raiz
                = (DefaultMutableTreeNode) m.getRoot();
        for (int i = 0; i < raiz.getChildCount(); i++) {
            if (((raiz.getChildAt(i).toString()).equals((p.getUniverso())))) {
                DefaultMutableTreeNode nodo = new DefaultMutableTreeNode(p);
                ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(nodo);
            }
        }
        m.reload();
        tf_nombre.setText("");
        tf_poder.setText("");
        tf_debilidad.setText("");
        cb_universo.setSelectedIndex(0);
        js_fuerza.setValue(0);
        js_fisica.setValue(0);
        js_hp.setValue(0);
        js_mental.setValue(0);
        JOptionPane.showConfirmDialog(jf_crear, "Personaje Agregado");
        jf_crear.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jb_agregarMouseClicked

    private void jb_listarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_listarMouseClicked
        jf_tree.pack();
        jf_tree.setLocationRelativeTo(this);
        jf_tree.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jb_listarMouseClicked

    private void jb_removeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_removeMouseClicked
        eliminar();
    }//GEN-LAST:event_jb_removeMouseClicked

    private void jb_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_eliminarMouseClicked
        jf_eliminar.pack();
        jf_eliminar.setLocationRelativeTo(jd_crud);
        jf_eliminar.setVisible(true);
        jd_crud.setVisible(false);
    }//GEN-LAST:event_jb_eliminarMouseClicked

    private void jb_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_removeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_removeActionPerformed

    private void jt_PersonajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_PersonajesMouseClicked

        //izquierda a derecha
        if (evt.isMetaDown()) {

            int row = jt_Personajes.getClosestRowForLocation(
                    evt.getX(), evt.getY());
            jt_Personajes.setSelectionRow(row);
            Object v1
                    = jt_Personajes.getSelectionPath().
                            getLastPathComponent();
            DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) v1;
             DefaultTreeModel m = (DefaultTreeModel) jt_Personajes.getModel();
              DefaultMutableTreeNode raiz
                = (DefaultMutableTreeNode) m.getRoot();
              for (int i = 0; i < 3; i++) {
                  if (nodo.equals(raiz.getChildAt(0))) {
                tabla();
                  }else if(nodo.equals(raiz.getChildAt(1))) {
                tabla();
                  }else if(nodo.equals(raiz.getChildAt(2))) {
                tabla();
                  }else if(nodo.equals(raiz.getChildAt(3))) {
                tabla();
                  }else {
                      for (int j = 0; j < 10; j++) {
                           if (nodo.equals((raiz.getChildAt(i)).getChildAt(j))){
                                Personaje s=((Personaje) raiz.getChildAt(i).getChildAt(j));
                               //metodo lista
                               listar(s);
                           }
                           } 
                      }
  
                  }
            }

    }//GEN-LAST:event_jt_PersonajesMouseClicked

    private void jc_select2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_select2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jc_select2ActionPerformed

    private void cb_selectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_selectMouseEntered
        String nombre=cb_select.getSelectedItem().toString();
            lmodel.removeAllElements();
        if (nombre.equals("DC")) {
            for (Personaje p : personajes) {
                
                p.setValid(true);
                lmodel.addElement(p);
             jl_elements.setModel(lmodel);
            }
        }else if (nombre.equals("Marvel")) {
            
        }else if (nombre.equals("Capcom")){
            
        }else{
            
        }
    }//GEN-LAST:event_cb_selectMouseEntered

    private void cb_universoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_universoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_universoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_select;
    private javax.swing.JComboBox<String> cb_universo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jb_agregar;
    private javax.swing.JButton jb_crear;
    private javax.swing.JButton jb_crud;
    private javax.swing.JButton jb_eliminar;
    private javax.swing.JButton jb_listar;
    private javax.swing.JButton jb_mod;
    private javax.swing.JButton jb_remove;
    private javax.swing.JButton jb_simulacion;
    private javax.swing.JComboBox<String> jc_select2;
    private javax.swing.JDialog jd_crud;
    private javax.swing.JFrame jf_crear;
    private javax.swing.JFrame jf_eliminar;
    private javax.swing.JFrame jf_simulacion;
    private javax.swing.JFrame jf_tree;
    private javax.swing.JList<String> jl_elements;
    private javax.swing.JLabel jl_nombre;
    private javax.swing.JSpinner js_fisica;
    private javax.swing.JSpinner js_fuerza;
    private javax.swing.JSpinner js_hp;
    private javax.swing.JSpinner js_mental;
    private javax.swing.JTree jt_Personajes;
    private javax.swing.JTable jt_listar;
    private javax.swing.JPopupMenu pp_listarlista;
    private javax.swing.JPopupMenu pp_listartable;
    private javax.swing.JTextField tf_debilidad;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_poder;
    private javax.swing.JTextField tf_pos;
    // End of variables declaration//GEN-END:variables
DefaultTableModel tmodel = new DefaultTableModel();

    ArrayList<Personaje> personajes = new ArrayList();
    DefaultListModel lmodel = new DefaultListModel();

    
    public void listar(Personaje p){
    lmodel.removeAllElements();
        p.setValid(false);
       lmodel.addElement(p);
        jl_elements.setModel(lmodel);
    
}
     public void tabla(int index){
         //nombre, poder, debilidad, universo, fuerza, afisica, amental, vida;
     while (tmodel.getRowCount()>0) {        
        tmodel.removeRow(0);
    }
         for (Personaje p : personajes){
             if (index==0) {
                 if (p.getUniverso().equals("DC")) {
                      Object[] row = {p.getNombre(),p.getPoder(),p.getDebilidad(),p.getUniverso(),p.getFuerza(),p.getAfisica(),p.getAmental(),p.getVida()};
                DefaultTableModel modelo = (DefaultTableModel) jt_listar.getModel();
                modelo.addRow(row);
                jt_listar.setModel(modelo);    
                 }
                
             } else if (index==1) {
                 if (p.getUniverso().equals("Marvel")) {
                      Object[] row = {p.getNombre(),p.getPoder(),p.getDebilidad(),p.getUniverso(),p.getFuerza(),p.getAfisica(),p.getAmental(),p.getVida()};
                DefaultTableModel modelo = (DefaultTableModel) jt_listar.getModel();
                modelo.addRow(row);
                jt_listar.setModel(modelo);    
                 }
             } else if (index==2) {
                 if (p.getUniverso().equals("Marvel")) {
                      Object[] row = {p.getNombre(),p.getPoder(),p.getDebilidad(),p.getUniverso(),p.getFuerza(),p.getAfisica(),p.getAmental(),p.getVida()};
                DefaultTableModel modelo = (DefaultTableModel) jt_listar.getModel();
                modelo.addRow(row);
                jt_listar.setModel(modelo);    
                 }
                
             } else if (index==2) {
                 if (p.getUniverso().equals("Capcom")) {
                      Object[] row = {p.getNombre(),p.getPoder(),p.getDebilidad(),p.getUniverso(),p.getFuerza(),p.getAfisica(),p.getAmental(),p.getVida()};
                DefaultTableModel modelo = (DefaultTableModel) jt_listar.getModel();
                modelo.addRow(row);
                jt_listar.setModel(modelo);    
                 }
                 } else if (index==3) {
                 if (p.getUniverso().equals("Mortal Kombat")) {
                      Object[] row = {p.getNombre(),p.getPoder(),p.getDebilidad(),p.getUniverso(),p.getFuerza(),p.getAfisica(),p.getAmental(),p.getVida()};
                DefaultTableModel modelo = (DefaultTableModel) jt_listar.getModel();
                modelo.addRow(row);
                jt_listar.setModel(modelo);    
                 }
                 }
         }  
    }
     
    public void eliminar() {
        DefaultTreeModel m = (DefaultTreeModel) jt_Personajes.getModel();
        DefaultMutableTreeNode raiz
                = (DefaultMutableTreeNode) m.getRoot();
        for (int i = 0; i < raiz.getChildCount(); i++) {
            for (int j = 0; j < raiz.getChildAt(i).getChildCount(); j++) {
                if (((raiz.getChildAt(i).getChildAt(j).toString()).equals((tf_pos.getText())))) {
                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).remove(j);
                }
            }
        }
        m.reload();
        jf_eliminar.setVisible(false);
        this.setVisible(true);
    }
}
